<?php

namespace AWD\FootballBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
    public function getActivePlayers($team_id = null)
    {
      $qb = $this->createQueryBuilder('p')
         ->where('p.expires_at > :date')
         ->setParameter('date', date('Y-m-d H:i:s', time()))
        ->orderBy('p.id', 'DESC');

      if($team_id)
      {
        $qb->andWhere('p.team = :team_id')
           ->setParameter('team_id', $team_id);
      }

      $query = $qb->getQuery();

      return $query->getResult();
    }
    //
    public function getTeams()
    {
        $qb = $this->createQueryBuilder('t')
        ->orderBy('t.id', 'DESC');
        $query = $qb->getQuery();
        return $query->getResult();
    }
    //
}
