<?php

namespace AWD\FootballBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends EntityRepository
{
    public function getWithPlayers()
    {
      $query = $this->getEntityManager()->createQuery(
        'SELECT t FROM AWDFootballBundle:Team t LEFT JOIN t.players p WHERE p.expires_at > :date'
      )->setParameter('date', date('Y-m-d H:i:s', time()));

      return $query->getResult();
    }
    //
    public function getCountTeams() {
        return $this->getEntityManager()
        ->createQuery('SELECT COUNT(t.id) FROM AWDFootballBundle:Team t')
        ->getSingleScalarResult();
    }
    //
    public function AllTeams() {
        $choices = array();
        $query = $this->getEntityManager()->createQuery(
        'SELECT t FROM AWDFootballBundle:Team t');
        $teams = $query->getResult();
        foreach ($teams as $team) {
            // I assume key is retrieved by getId
            $choices[$team->getId()] = $team->getName();
        }
        //
        $choices['not closed'] = 'Not closed';
        return $choices;
    }
   
    //
     
    //
}
